# Generated by Django 4.2.1 on 2023-09-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagementmodel',
            name='studyarea',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
