# Generated by Django 4.2.1 on 2023-09-04 10:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_usermanagementmodel_studyarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagementmodel',
            name='usehistory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=8),
        ),
    ]
